### ISSUE TITLE
Использование кавычек в строковых параметрах Gherkin

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#1]
Имеем в Gherkin: возможно указать строковый параметр в формате

```Gherkin
Тогда значение поля стало "ООО "Мечта""
```

Проблема: Кавычки с кавычками не обрабатывается языком 1С, а точнее логика такой обработки будет нетривальной .

Противоречие 1: Можно перейти на формат двойных обрамляющих кавычек, но тогда бизнес-аналитик лишается магии Gherkin
Противоречие 2: Можно перейти на апострофы, но тогда что делать тогда когда в строке появится апостроф как символ.

Необходим такой идеальный конечный результат, который позволит бизнес аналитику не использовать магию обрамляющих символов, однако позволит программно обрабатывать такие параметры корректно.

**Comment by allustin** [comment]
Пока выкрутились через апострофы https://github.com/silverbulleters/vanessa-behavior/issues/162

**Comment by Hissin** [comment]
Проблемы возникнут при использовании любых символов. Мы можем логически вычислить какая первая кавычка в строке, а какая последняя? не могу придумать ситуацию, когда мы будем использовать два строчных параметра в одной строке сценария. Если такой ситуации не будет, мы можем брать первую и последнюю как обрамляющие, а все что внутри как сама строка

**Comment by Hissin** [comment]
Или может кто придумает, когда в одной строке будет два строчных параметра? тогда сейчас придумаю другой вариант обрамления

**Comment by allustin** [comment]
@Hissin тут так просто не получится - нужно взглянуть глазами бизнес-аналитика и разработчика.

Однако - наши любимые бизнес-аналитики не очень любят писать ожидания в конкретных терминах, они любят писать "Тогда все хорошо"

А все хорошо - это вложенный сценарии. И уже вложенный сценарии расшифровывается - что это значит "всё хорошо". И он уже низкоуровневый.

Однако, низкоуровневые сценарии разработчик тоже не любит писать. А кнопконажималка как раз фиксирует строковых величин. 

Если коротко - то нужно взглянуть всесторонне, особливо на соседей из зоны speclog, behave и cuсumber - как они решают эту проблему.

P.S. Задачи в архитектурный комитет так просто не решаются, поэтому давай не торопится - сейчас выкрутимся в виде апострофов, но это костыль - главное не забыть его обдумать и исправить.

**Comment by Hissin** [comment]
@allustin принято. Только вопрос. В верхнеуровневом сценарии не предполагается использование кавычек. по крайней мере мне будет неудобно. Ибо общение с заказчиком не подразумевает использование конкретных значений. А если и подразумевает, то накидывать данные параметры будем в эдиторе. Тогда мы можем их все сделать в виде расшифровки, которую мы можем вынести. Например: И тогда наименование стало "Вынесенный во вне Параметр". И тогда обрамление вообще не понадобится. При возникновении символов используемых в стандартном языке Геркина сразу переводить в параметр. 

И хорошо что не берем в рассмотрение сам 1С.

**Comment by Hissin** [comment]
Ну и соответственно так же можем поступить и с низкоуровневыми сценариями. Которые все равно будет писать и бизнес-аналитик и разработчик/архитектор вместе. Ибо так правильно.
соседей гляну

**Comment by allustin** [comment]
Тип задачи: "Конкретная"

Общая формулировка: Необходимо *единообразно обозначить строковые параметры в Gherkin* однако отсутствует *символ обозначающий границы строковых параметров* и всё это нужно *к практикуму в марте* , чтобы обучение было правильное

Противоречие 1: Требуется выбрать символ обрамляющий строку, однако когда выбираем один символ, внутри строки мы его не можем использовать как часть строки.

Аналоги "в соседнем мире": 

* Cucumber - https://cucumber.io/docs/reference
  используются управляющие строки
 """
 <ЛюбаяСтрока>
 """ 
где неразрывные три кавычки в строке, начинаю строковый параметры. больше в строке нет никаких символов - только пробелы и табуляции. 

* SpecFlow - https://github.com/techtalk/SpecFlow/wiki/Using-Gherkin-Language-in-SpecFlow
используются 2 управляющих символа с маленькой вероятностью появления в реальной строке например пара Апостроф+Меньше ('<) и Больше+Апостроф (>')

**Идеальный конечный результат позволяет определить символ для обрамления строковых параметров, и позволяет его же использовать внутри строки**

Системный решатель:

* Задача "надсистемы": Язык описания обрамляет автоматизированные строковые параметры
* Антизадача "надсистемы": **Автоматизированные строковые параметры обрамляют язык описания**
* Задача "системы": Шаг сценария обрамляет содержание строкового параметра
* Антизадача "системы": Строковый параметр обрамляет шаг сценария 
* Задача "подсистемы":  Код символа обрамляет и участвует в строке 
* Антизадача "подсистемы": Строка участвует и обрамляет код символа

Формулировка решения:

Язык описания строк - это очень похоже на RegExp. Собственно на них построена вся работы Gherkin. Одновременно с этим обрамление должно быть человекочитаемым как можно больше. Поэтому для реализации я бы предложил ввести три определения

Бывает *слово*, бывает *предложение*, бывает *текст*. В слове не бывает знаков препинания ;-)

Функционал: 

* слово - обрамляется кавычками
* предложение - обрамляется символами предложения /ООО "Рога и Копыта" Филиал г. Бийск\?/
* длинный текст - обрамляется символами """  и """ в отдельных строках
 
Состав: Функция разбора шага ищет Слова, Предложения и Тексты в составе шага и их считает параметрами сниппета

Поведение:
ШагНайтиДлинныйТекстКакПараметр()
ШагНайтиПредложениеКакПараметр()
ШагНайтиСловоКакПараметр()

обрамление предложения потенциально ведет наших любимых разработчиков к пониманию RegExp, а для бизнес-аналитика просто особенности использования Gherkin

~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик"
* "Красно-эмоциональный матерщинник"
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист"
* "Зеленый нарцисс творец"
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by allustin** [comment]
Запись решения и обсуждения https://youtu.be/EnCMKP1PrtM

@Pr-Mex - наверное надо будет потом написать feature в виде задачи для релиза 1.1

**Comment by alehinsasha** [comment]
https://github.com/cucumber/cucumber/wiki/Gherkin

По определению, Gherkin - линия-ориентированный язык, использующий отступ для определения структуры. Т.е. никаких символов! Новая строка начинается с ключевого слова, и как бы всё на этом.
