### ISSUE TITLE
Хранение внешних по отношению к конфигурации инструментов

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#10]
automigrated to xdd forum

**Comment by Hissin** [comment]
**Тип задачи:** 

**Общая формулировка:**

**Противоречие 1:** 

**Идеальный конечный результат** 

**Аналоги "в соседнем мире"**

**Системный решатель:**

* Задача "надсистемы": 
* Антизадача "надсистемы": 
* Задача "системы": 
* Антизадача "системы": 
* Задача "подситемы": 
* Антизадача "подсистемы": 

**Формулировка решения:**


**Функционал:**



**Состав:**



**Поведение:**



~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик"
* "Красно-эмоциональный матерщинник"
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист"
* "Зеленый нарцисс творец"
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by allustin** [comment]
Как оказалось, многие даже не понимают проблематики - то есть не сталкивались.

https://youtu.be/Gqgk9eBpy2I

Отложим на месяц - хотя в рамках предварительно для таких целей я сейчас использованию специальный домен binary.vanessa.services. Посмотрим на практику применения и тогда вернемся к вопросу.

**Comment by allustin** [comment]
берем очередной раз в разбор.

**Comment by allustin** [comment]
http://www.scaledagileframework.com/devops/

в SAFe на этот вопрос осторожно "забили"

"Где-то хранятся внешние компоненты и бинари" и всё.

Единственное где решали такую задачу:

* это скорее Maven и концепция artefactory
* и конечно некое ObjectStorage доступное через API

**Comment by allustin** [comment]
@pumbaEO https://git-lfs.github.com/ - собственно, не оно ли это ?

и сюда же https://github.com/github/lfs-test-server

и сюда же https://github.com/github/git-lfs/wiki/Implementations

**Comment by allustin** [comment]
Source Tree выпустил поддержку GIT LFS

Стабильной реализации GIT-LFS сторонними средствами пока не обнаружено - оставляю на потом. Ориентир "на потом", как только появится что-то стабильное, которое можно развернуть локально или в облаке.
