### ISSUE TITLE
Версионирование feature-файлов

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-services#11]
Возник вопрос/необходимость.

Функционал: Версионирование feature-файлов

    Как системный аналитик
    Я хочу хранить версии изменения feature-файлов 
    Чтобы знать историю изменения функционала
    И могу предоставить информацию заказчику, если возникают конфликты

Контекст:

    Дано: BDD-Editor

Сценарий:

    Когда я нажимаю кнопку "Загрузить feature-файлы" 
    Тогда загружаются последние версии feature-файлов

    Когда выделен feature-файл
    И я нажимаю кнопку "Загрузить версию feature-файла"
    Тогда выводится окно всех версий feature-файла с датой версии
    И я выбираю версию необходимую мне
    И открывается выбранная версия файла

Есть вопросы:
1. Стоит ли это делать? (для аналитика и разработчика - это уменьшение рисков)
2. Как хранить отличия от первоначального feature-файла, стоит ли это делать?
3. В каком виде, где и как хранить версии?

**Comment by allustin** [comment]
Я вроде как знаю ответ на твой вопрос - это концепция git flow

По серьезному нам от неё никуда не деться.

Данное противоречие звучит скорее всего так.

Если Gherkin создан для того чтобы быть читаемым не ИТ специалистами
То тогда должно возникнуть что-то адаптирующее git-flow для не ИТ специалистов.

Тут вопрос лежит в плоскости "управления изменениями" и "релизном управлении".

Пока писал понял - что нужно скорее всего рассмотреть этот вопрос в течении следующего месяца.

**Comment by Hissin** [comment]
@allustin  - по хорошему это тянет на объемный проект, как "Правильная среда Аналитика" :)

**Comment by allustin** [comment]
Решено что это будет "обертка" над:

* git blame ./feature-name
* git log ./feature-name
* git stats ./feature-name
* git checkout abcde

поэтому - это собственно не противоречие ;-).
