### ISSUE TITLE
Определения

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-services#12]
automigrated to xdd forum

**Comment by allustin** [comment]
Нужно будет чуть расширить описание - в чем проблема.

Терминология процесса - это одно
Терминология инструментов - это другое

И т.д.

Скорее всего это выродиться в страницу - "словарь понятий" где-нибудь тут http://vanessa.services/docs/intro

Если я тебя правильно понял

**Comment by allustin** [comment]
@alehinsasha - на досуге давай попробуем расшифровать, в чем противоречие. Чтобы вывести вопрос на архитектурный комитет 30-го числа

**Comment by allustin** [comment]
@alehinsasha извини - но задача переносится - я так понимаю пока не до её расшифровки. А без расшифровки мы такое не берем

**Comment by allustin** [comment]
Еще раз попробую коснуться задачи

* "билды" или "сборки"
* "континиоус интеграция" или "непрерывная ?"
* "континиоус деливери" или "непрерывная ?"

фича-файлы или файлы функциональности

у меня есть свое мнение, но я его придержу до финального обсуждения

я уже не говорю про стори-поинты и другую SCRUM веселуху

**Comment by Hissin** [comment]
**Тип задачи:** Абстрактная

**Общая формулировка:** Необходимо договориться об общепринятых внутри (снаружи?) терминах, определениях и формулировках совместимых и понятных для российских пользователей, но не отходя далеко от общемировых

**Противоречие 1:** использование разных терминов к одному объекту приводит к недопониманию при общении внутри (взаимопонимание)
**Противоречие 2:** может привести к отделению от общепринятых терминов в мире
**Противоречие 3:** несколько методологий и технологий используемых при работе, которые используют одно значение/тип, но разную терминологию

**Идеальный конечный результат** 

* принят единый совместимый и понятный формат используемых терминов и определений, который будет понятен в любой из используемых методологий и технологий

**Аналоги "в соседнем мире"**

* 

**Формулировка решения:**

* 

**Состав:**



**Поведение:**


~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик" 
* "Красно-эмоциональный матерщинник" 
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист" 
* "Зеленый нарцисс творец" 
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by alehinsasha** [comment]
Новичкам будет трудно усваивать материал если одно и то же будет называться по разному. Формулировку задачи Катей - одобряю) Это просто условности на которые нужно пойти чтобы облегчить вход новичков в мир BDD.

**Comment by allustin** [comment]
Надо сделать единую коллективную таблицу - в формате Markdown

Термин | Перевод | Начинающий  | Профессионал  | Специалист
--- | --- | ---  | --- | --- 
Feature | Функционал, Функция, Свойство | Файл на языке Gherkin |  Набор процедур проверки  |  Сценарий демонстрации 
Story |   |   |   | 
Story point |   | Идеальное время на задачу  |  Попытка угадать за сколько я сделаю задачу  |  Абстрактный "попугай" оценки вброса
Build | Сборка  |   |   | Сборка продукта в один шаг 
<термин> |   |   |   | 

И выработать стиль кодирования

```
Процедура СделатьБилд() //не корректно
Процедура ЗапуститьСборкуПродукта() //корректно
Procedure MakeBuild() //корректно
```

```
КоллекцияФичаФайлов = Новый Структура();
КоллекцияФайловСвойствСистемы = Новый Структура();
```

**Comment by allustin** [comment]
Предложение - новые товарищи - могут добавить термин для последующей расшифровки.

**Comment by nixel2007** [comment]
> Функционал

Функциональность же.
Как вариант - "особенность". Коллективная вики? Репозиторий?

**Comment by Hissin** [comment]
@nixel2007 да, коллективно будем заполнять

**Comment by alehinsasha** [comment]
@nixel2007 для профессионала - можно, но для начинающего было взято из https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json#L2170

**Comment by nixel2007** [comment]
@alehinsasha позволю себе чуть позанудствовать.
[Функционал](https://ru.wikipedia.org/wiki/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB)
[Функциональность](https://ru.wiktionary.org/wiki/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C)

**Comment by Hissin** [comment]
@nixel2007 Добавила и функциональность в табличку. но функционал необходим для соответствия Gherkin, т.к. их локализация есть и она уже живет в таком виде.

**Comment by nixel2007** [comment]
@Hissin вроде ничего не мешает добавить в i18n самого gherkin?

**Comment by alehinsasha** [comment]
@nixel2007 @Hissin Убрал "Функциональность" т.к. для начинающего было взято от сюда https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json#L2170 ТОЧКА. Редактируйте профессионала и специалиста.

**Comment by Hissin** [comment]
@alehinsasha В переводе мы используем все возможные вариации, а вот что это такое и какое несет в себе определение уже идет по степеням "Начинающий", "Специалист", "Профессионал".
В переводе должны присутствовать все вариации термина, чтобы пришедший понимал к чему относится перевод

**Comment by allustin** [comment]
https://youtu.be/0FbEp05AHxM

**Comment by nixel2007** [comment]
> холиварный оффтопик
`https://github.com/cucumber/gherkin/pull/165`

**Comment by allustin** [comment]
@nixel2007 :100: . Шо то я забыл, что можно сразу в "огурец" добавить.

**Comment by alehinsasha** [comment]
@Hissin согласен, но google translator выдал много больше вариантов перевода слова feature:

~~~
*сущ.

особенность
черта
характеристика
свойство
признак
характерная черта
деталь
полнометражный фильм
черта характера
сенсационный материал
местный предмет
аттракцион
черта лица
гвоздь программы
большая газетная статья
большая статья в газете
подробность рельефа местности
боевик
основной фильм кинопрограммы

* глагол

показывать
напоминать чертами лица
изображать
выступать в главной роли
быть характерной чертой
показать на экране
выводить в главной роли
набрасывать
рисовать
зарисовать
обрисовывать
исполнять главную роль
отводить важнейшее место
делать гвоздем программы
походить
~~~

какие-то варианты перевода можно отбросить сразу, но случаи и слова разные могут быть, как будем определять, какие варианты перевода добавить? или будешь настаивать что в колонку перевод нужно писать все возможные варианты?

**Comment by Hissin** [comment]
@alehinsasha а можно исключить "троллинг"? записываем только те, которые сами используем или используются "рядом"

**Comment by alehinsasha** [comment]
@Hissin Кать, без троллинга. Мы сейчас договоримся, и люди (читая обсуждение) будут в курсе что да как.

**Comment by Hissin** [comment]
@alehinsasha тогда официально ограничиваемся теми определениями и переводами, которые используются применительно к данной области ADD у нас и по России

**Comment by alehinsasha** [comment]
@Hissin OK!

**Comment by allustin** [comment]
Закрою задачу - переходим на форум для обсуждения
