### ISSUE TITLE
Что делать с TDD'шникам

### ISSUE THREAD

**Issue by g-ones** [silverbulleters/vanessa-services#14]
Запрещать ли писать через TDD ?

**Comment by Hissin** [comment]
На верность не претендую, но мнение выскажу.
В моем понимании и видении мира существует два подхода:

1.  Сверху (Gherkin), Середина (BDD), вниз (TDD)
2.  Снизу (TDD), Середина (BDD), вверх (Gherkin)

И все остальные, которые берут какой-то из этих участков и что-то там "используют" в своем "мире".
Но, насколько корректным является второй подход - вопрос спорный. Все вычисляется областью применения.
Поиграем в "Что было раньше - курица или яйцо?" ;)

1. "В начале было Слово"
Приготовим всем понятную яичницу ;)
Любой процесс создания "яичницы" начинается с мысли "я хочу поесть". 
Первый шаг к цели сделан. Мы сформировали желание. Далее мы начинаем думать, а чего бы мы хотели поесть? И выбрали "яичницу". Ага. Уже конкретизировался первоначальный запрос и мы можем понять, что нам надо для приготовления "яичницы". яица, соль, сковороду и масло.
И вот чтобы это все приготовить мы должны проверить, а все ли у нас есть для этого. И только после этого мы если чего-то не хватает идем в магазин, докупаем и только потом готовим "яичницу". Логично?

Переводим все это на наш язык :)
Первоначально создается запрос или требование. (Gherkin)
Далее анализируем и конкретизируем запрос, что именно мы хотим и в каком виде(Gherkin). Делаем проверку на желаемый результат. Не получаем  его! (BDD)
И только потом реализуем требования в код по заранее известным конечным целям (TDD)

Фактически первый подход является логичным, верным и правильным.

2. "А все таки, что было первым?"
Из яичницы ингредиенты конечно обратно не соберем... Но логически подумать можем. 
В каком случае может возникнуть "яичница" из ниоткуда? Только когда вам кто-то ее приготовил и принес, не сказав и не объяснив из чего она сделана, а вам надо понять, будете вы ее хотеть есть или нет.. Но опять таки... а отвечает ли она вашим желаниям? 
И опять вернулись туда же. А какие ваши требования были к "яичнице"? Может это "болтунья", а вы хотели "глазунью". Опять таки нарываемся на изначально сформированные требования для конечного "я хочу поесть".
Ну или же получается второй вариант: принесли и сказали "ешь что дают", "не понравится, будем ее же просто пережаривать". 

Переводим все это на наш язык :)
Есть нечто, которое мы "покрыли" TDD
Потом формируем на основании этого проверку на желаемый результат, который сформировался исходя из того что есть в этом нечто (BDD)/
И потом формируем требования самому заказчику, что он хотел вот именно этого (Gherkin).

А теперь подумаем... как быть заказчику?
Конечно у нас сейчас преобладает второй вариант, когда просто заказчика ставят перед фактом, что вот такая "яичница" должна быть и она правильная. А много ли заказчиков хотят, чтобы, как минимум так продолжалось, как максимум не хотят, чтобы им навязывали свою "яичницу". Ведь кто платит, тот и заказывает.

Мой вывод: первый вариант рулит ;)

**Comment by allustin** [comment]
@Hissin - а можно я это на стенку повешу ? мне как то и добавить нечего.

**Comment by Hissin** [comment]
@allustin конечно

**Comment by artbear** [comment]
@Hissin Хорошие слова написаны, но весьма лукавые :)

Но вот с чего вы вдруг решили, что TDD это исключительно низкоуровневые тесты и/или тесты без выяснения поведения системы ? где это написано?
Если очень кратко, то:
смысл TDD как раз в изучении поведения системы и реализации этого поведения
тесты рождаются не просто так, исключительно по "произволу" разработчику, они рождаются после изучения требований заказчика к системе и служат для повышения качества системы.

@wizi4d @EvilBeaver @kuntashov Что-то добавите?

**Comment by EvilBeaver** [comment]
Ох, как же я люблю холивары, которые ничего не решают!

Давайте, конечно же! Но лучше про это спорить лично, на посиделках (возможно, нетрезвых)

Итак: @Hissin конечно же, лукавит. Или рассматривает только сценарий, когда есть уже готовый код, и его надо покрыть тестами - непонятно как и зачем.

А идея любого букваDD - код писать в конце, а сначала понять, как **поведение** этого кода потом проверить, задокументировать, да еще так, чтобы документация автоматически не  "протухала". 

Короче, мое мнение - тестов, действительно нет. А есть код, который валидирует другой код. И этот код либо написан на одном языке (который язык системы), либо на другом (который Геркин). А бывает, что вообще, как в Go, когда прямо на Go пишут код, но он как-бы фича (забыл название, @allustin знает). Вот оно - какое DD?

Мой вброс в холивар, стало быть, такой - **а как вы вообще отличаете TDD от BDD?** Где заканчивается одно и начинается другое? Один пёс, "все есть код" и, как правильно заметил, @wizi4d, пишут его инженеры (@allustin, по качеству, ага)

**Comment by Pr-Mex** [comment]
Если пишем модуль, dll, или подобное - рулят модульные тесты.
Если пишем сложное поведение системы - рулят сценарии поведения.
Для каждой задачи - свой инструмент.
В 1С второго больше чем первого.

**Comment by kuntashov** [comment]
На всякий случай, раз упомянут, скажу, что я пас (хотя бы потому что ни по TDD, ни по BDD в их чистом виде не разрабатываю, поэтому необходимой экспертизы нет, ничего нового для собравшихся гуру сказать не смогу), но спасибо за подписку, почитаю вечером :)
p.s. Если что, как сторонний наблюдатель, я не понял исходного посыла - "запрещаем". Никогда не считал, что TDD и BDD взаимоисключающие методики независимо. 

@Pr-Mex  :+1:

**Comment by artbear** [comment]
>Если пишем модуль, dll, или подобное - рулят модульные тесты.
Если пишем сложное поведение системы - рулят сценарии поведения.
Для каждой задачи - свой инструмент.
В 1С второго больше чем первого.

Все давно придумано до нас :)
В мире программирования в качестве дубля фразы "рулят сценарии поведения" давно используется "рулит приемочное тестирование" :)
Как вы знаете, я уже очень давно не говорю модульные тесты, а использую для 1С термин "тесты" и "приемочные тесты"

@EvilBeaver а как называется код, который валидирует другой код? Тест :) 

Так что от тестов нам никуда не деться!

Семантика-то все равно остается неизменной , как ни называй :)

**Comment by wizi4d** [comment]
Все, что я хотел сказать на эту тему, я уже сказал в статье на хабре про корнишон и поиск целевой аудитории:
> Так же хочу отметить, что, на мой взгляд, тесты из квадрантов 1 и 2 (Q1 и Q2) ни в коем случае не должны противопоставляться, они прекрасное дополнение друг к другу!
Тесты первого квадранта дают такой замечательный артефакт, как качественный дизайн программного кода.
Тесты второго квадранта дают уверенность в том, что бизнес получит то, что он ожидает, а не то, что получилось.

В данном контексте можете рассматривать Q1 как TDD, а Q2 как BDD.

**Comment by awk-kazmin** [comment]
А вы не забыли про роли?

Заказчик
Руководитель
Бизнес-аналитик
Архитектор
Программист
Тестировщик
Внедренец
Технический писатель
Администратор

Мы как эти роли в контексте рассматриваем? Просто если брать "чистого" программиста, то ему геркин "по барабану". У него unit тесты (в лучшем случае) его все.

Если брать заказчика ему то же геркин "фиолетов", он для разработки использует целую команду "дормоедов".

**Comment by artbear** [comment]
@awk-kazmin Об этом и пишет @wizi4d в своей статье на хабре https://habrahabr.ru/post/275013/

**Comment by awk-kazmin** [comment]
Прочел. Мы говорим об отделах тестирования?

**Comment by allustin** [comment]
@awk-kazmin мы нет точно. в своих проектах по внедрению мы переформатируем отделы тестирования в отделы контроля качества во главе с релиз менеджерами.

@g-ones как ты правильно заметил:

есть 2 момента

<что-то>DD - концепция которая нам говорит, что в процессе мы должны руководствоваться неким <что-то> как основой процесса производства.

кто-то руководствуется:

* тест вначале -  тогда получается TDD
* проверка поведения вначале - тогда получается BDD. @EvilBeaver  http://goconvey.co/ эта хрень называется - через 6 месяцев ожидается встраивания в экосистему cucumber, там идут активные переговоры
* Gherkin спецификация вначале

И вот с последним будут проблемы - нужно смотреть уже в методику организации процессов - Agile, SCRUM, Kanban, Lean, SAFe, CI-CD

Дело в том что согласно концепции на 2015 год - любые требования к продукту, к программе продуктов да и вообще должны быть автоматизированы.

Концепция называется ADD, где A внутренняя автоматизация **всего**

И ключевое будет что мы запрещаем использовать семантически слово "тест" и однокоренные, даже сами себе. Чтобы думать о поведении.

И кстати - @Hissin давай посмотрим как получится донести эту мысль через решения задач специалиста 1С.

я попробую к субботе преобразовать все аргументы в единый документ для обсуждения на архитектурном комитете.

**Comment by awk-kazmin** [comment]
@allustin А как выглядит данный отдел? Какие в нем есть роли? Что эти роли выполняют? Много ли таких отделов существует в природе?

**Comment by allustin** [comment]
@awk-kazmin меня опасно об этом спрашивать - я сейчас включу свою платную деятельность консалтера и дальше 8 часов видео с разрывом мозга. Поэтому по пунктам:

* в общем случае вот так http://www.scaledagileframework.com/release-management/
* там же по ссылке и роли
* мои стараниями уже 5-ть.

**Comment by artbear** [comment]
@allustin 
>тест вначале - тогда получается TDD
проверка поведения вначале - тогда получается BDD

Опять лукавим?
"тест" всегда семантически равен "проверка поведения"
Если рассматривать все как код, BDD и есть TDD :)

**Comment by allustin** [comment]
@artbear Я попытаюсь решить противоречие через ТРИЗ к субботе сгруппировав все в формат архитектурного решения. Мне самому интересно что получится.

**Comment by Hissin** [comment]
@artbear  - Хорошо. давайте немного расширим для понимания. 

По изначальной методике разработки через TDD было принято - проверка "кодом код", что уже само по себе является инструментом разработчика, как таковой, но что и понятно, ведь разработчик проверяет сам себя. Если взять это понятие шире, то в системе "полной жизни" проекта/продукта является низкоуровневым методом. Методика TDD подразумевает проверку поведения кода и проверку поведения элементов кода к какому-либо условию. Но не подразумевает под собой целостной проверки "А зачем вообще это было надо?". По крайней мере, судя по информационным источникам и длительным трениям между специалистами, вывод получается такой. И в принципе на практике оно так и получилось. Т.е. фактически, оно конечно надо было, чтобы вернулось "True", но какие последствия от этого "True" непонятно, и зачем именно "True" должно было вернуться тоже не ясно.

Теперь поднимаемся выше. @awk-kazmin  Я как раз таки рассматриваю **свою** "яичницу" с точки зрения всех ролей в "полной жизни" проекта/продукта. Поэтому и написала два сценария развития "приготовления яичницы". Но видимо немного недописала второй сценарий. Чтобы @artbear уловил смысл. Допишу сейчас.
Первый подход подразумевает логичное развитие событий от Заказчика до Кодера (именно кодера, т.к. есть разные стадии разработчика). 

Второй подход подразумевает подход начала проверки "кодом кода", т.е. фактически мы проверяем, что яйцо это на самом деле яйцо, и что яйцо оно куриное, а не страусиное. И также можем проверить, что оно у нас есть.
И мы не отходим от разъяснения @EvilBeaver , что любое что-тоDD это проверка поведения. Просто TDD это низкоуровневая проверка целостности кода системы, но не логики системы, которую в нее вкладывают уровни вроде "Заказчик", "Аналитик" или "Архитектор" и т.д..

Т.е. фактически разница смысла, уровня, необходимости и понятия что-тоDD.
Конечно можно использовать TDD на чуть большем уровне, с какими-то зачатками BDD, но он не выйдет на ту же методику в полном объеме, ибо тогда это уже будет BDD, и тут придется либо менять взгляды и использовать полноценное BDD, ломая систему и создавая новую "жизнь", либо мучиться и скрипеть на TDD с отрывками наличия BDD, пытаясь наладить какую-то связь с "внешним миром".

Поэтому описанные мной цепочки не исключают TDD из BDD. BDD продолжает использовать TDD, но выводит его на другой уровень и объединяет все звенья цепи "жизни" проекта/продукта, конечно отчасти меняя логику TDD. Фактически от TDD остается проверка "кодом кода", но уже осмысленная проверка с логикой, целью и смыслом этого кода. И вот тогда мы уже готовим правильную, вкусную и понятную "яичницу" для всех.

При этом убивая много других зайцев, от проверки кода на целостность (что "яичница" приготовилась по рецепту и не пригорела) и смысловую нагрузку (зачем вообще мы готовили "яичницу" и какая она должна была быть), автодокументирования (рецепт приготовления "яичницы") и до демонстрации любому заказчику/покупателю (посмотрите какая клевая "яичница" получется по нашему/вашему рецепту). И тут вот уже можно и нужно взглянуть на это под взглядом ADD. С методики BDD легче будет "увидеть" и перейти к ADD, если я не права поправь меня @allustin .

@allustin  - ты имеешь ввиду решение задачи сделать в обоих подходах, описанных выше? Тогда у меня встречное предложение. Почему бы это все не сделать максимально автоматизировано с зачатками ADD? ;)

**Comment by artbear** [comment]
@Hissin хорошо написала, но опять же с упором на то, что только с появлением БДД началась на зайцев и научились жарить яичницу. 
А ведь этих зайцев давно нашли в лесу, поймали и зажарили еще до появления БДД :)

Посмотрим на 
>+ Первоначально создается запрос или требование. (Gherkin)
>+ Далее анализируем и конкретизируем запрос, что именно мы хотим и в каком виде(Gherkin). 
>+ Делаем проверку на желаемый результат. Не получаем его! (BDD)
>+ И только потом реализуем требования в код по заранее известным конечным целям (TDD)

Каждый из указанных пунктов всегда выполняется при работе с требованиями заказчика у грамотных/опытных специалистов.
степень формализации зависит от команды.

Например, как обычно работает любая команда
>поговорили с заказчиком, узнали, что он хочет
>формализуем его хотелку в нужном виде (языков спецификаций на самом деле множество)
>проверяем, не реализована ли хотелке в системе
>реализуем и тестируем вручную

Как видим, абсолютно те же элементы :)

Я согласен, что БДД это хорошо, я сам люблю писать много текста и спецификаций.

Главное, что мне не нравится - вы всячески противопоставляете БДД и ТДД :(
"до БДД ничего не росло, а вот с БДД ваши волосы станут ..." :)

**Comment by artbear** [comment]
@Hissin пятница, поэтом пишу расслабленно и, наверное, сумбурно :)

**Comment by allustin** [comment]
@artbear я пока пишу по ТРИЗ и не хочу вдаваться в спор, но коллизия в том, что должно быть вначале:

Spec first (Gherkin)
Convey first (BDD)
Test first (TDD)

противоречие именно в этом - завтра посмотрите что получилось по АРИЗ и в режиме критики по методу шести шляп.

**Comment by artbear** [comment]
@allustin Так фишка же в том, что ИМХО никто же не спорит, что сначала нужна некая формализация требования от заказчика и поведения будущей системы.
Все идут от поведения, только инструменты у всех разные.

Мне самому нравится идея большей формализации требований с самого начала сборка этих требований и явная связь с кодом.

Ты же знаешь, что, например, я для PowerShell писал в свое время в формате BDD с помощью проекта [Pester](https://github.com/pester/Pester)

Вы делаете правильное/нужное дело, мне только лишь не нравится, что явно противопоставляете БДД и другие виды тестирования :(

**Comment by Hissin** [comment]
@allustin хорошо. 
Временно прекращаем обсуждение, до новой порции информации :)

**Comment by allustin** [comment]
В этот раз я поступлю по другому, я начну с критических высказываний

Итак что мы имеем на 2016 год, так сказать на его начало.с точки зрения критики общего движения в сторону ADD в 1С.

я группировал все что проходило на наших проектах внедрения и в социальных сетях, часть критических замечаний взята у участников этой дискуссии - что ни коим образом не означает что они плохие, они просто критические. Причем я их сгруппировал в 2 категории:

### Критические замечания владельцев активных аккаунтов на github в SB и XDD и связанных с ними через социальный граф GitHub 

> так как я занимаюсь BI - есть у меня такой веселый инструмент для анализа, для построения социальных графов

* "Ghekrin не нужен" 
* "Gherkin нужен но не мне" 
* "Gherkin" 

### Критические замечания от обычных 1С-ников

> а есть и такие - тысячи их

* TDD в 1С нужен только для создания своих типовых
* BDD нужен только для создателей своих типовых
* Gherkin не удобен для заказчика
* 90% времени 1С-ника занимает борьба с производительностью решения и внедрением типовых а не с программированием вообще
* внедрение ERP 2.1 на заводе требует только 20% расходов на разработку, остальное на внедрение - поэтому TDD, BDD, Ghekrin не нужно
* пусть этим занимается сама компания 1С - её продукты и платформа: пусть и развивают автоматизированные инструменты

есть еще критические высказывания что в:

* в 1С не нужен SCRUM
* в 1С не нужен Agile

они связаны с нами - так  инженерные практики ADD родом как раз оттуда
но мы это опустим - принимая как правило, что нужно ибо Time To Market никто не отменял (что это такое смотрите выступление Грефа про дауншифтеров) 

@all - так как ТРИЗ никому не интересен кроме меня и @Hissin то я буду публиковать информацию порциями. выжимая из АРИЗ сегменты

@g-ones ответ на твой вопрос будет дан в конце.
поэтому пока заблокирую обсужение

**Comment by allustin** [comment]
Итак мы исходим из того что решение уже существует - и лаконично оно называется ADD.

Но еще раз разберемся с критическими высказываниями.

### Начнем с конца - с обычных 1С-ников.

Учитывая что они действительно правы: в 1С **не нужна** вся эта ересь, когда ты внедренец закончивший курсы на Специалиста 1С и научившийся писать `Для каждого ЧтоТоТам и ГдеТоТам Цикл`
Но нам нужно что сообщество 1С-ников развивалось и создавала более качественные продукты - такова наша социальная миссия ;-)

В итоге у нас возникает противоречие 

```
Нужно Gherkin, BDD, TDD, Git, 
НО не нужно 
Gherkin, BDD, TDD, Git
```

и второе - ведь действительно - основная работа обычного 1С-ника в России имплементация типовых. C другой стороны они там имплементируют, но мы то знаем, что потом это уже не доработаешь - потому что имплементары делают вот такое:
![](http://infostart.ru/blogs/data/0000171/images/large/fetch.jpg)

скриншот из семерки, но если бы был Gherkin, BDD, TDD, то такого бы не было или как минимум рафакторинг был был проще.

Я специально (в основном для себя, чтобы иногда возвращаться к корням держу эту статью) http://infostart.ru/public/16966/ - @g-ones почитай на досуге.

поэтому я перефразирую

```
Нужно внедрять типовые и не нужно Gherkin, BDD, TDD, Git
НО не нужно внедрять типовые
Нужно Gherkin, BDD, TDD, Git
```

### Продолжим уже "с нашими" с Github

они тоже правы только противоречие выглядит по другому

Gherkin как уже было многократно говорено - дополнительный слой абстракции. А "все абстракции текут" (с) 
Знающие люди - очень не любят лишние слои абстракции. Собственно сама платформа 1С - только слой абстракции ;-). А учитывая что знающие люди и я в том числе в свое время побывали "в шкуре" обычных 1С-ников - они очень не хотят делать что-то что приведет к скриншоту выше.
НО
лишние слои абстракции нужны - иначе как тогда возникли C#, Groovy, ORM реализации и т.д. Они же создавались под проблему ? Значит нужно быть готовым к этой проблеме - а она возникнет обязательно по "Закону Мерфи"

"Есть проблема - есть язык" (с)

Итак в итоге я бы сформулировал следующее

```
Пока нет проблем Ghekrin не нужен
НО 
Gherkin нужен так как проблема возникнет обязательно
```

но дополнительно я бы сказал следующее, есть еще одно противоречие

есть проблема "принятия неверных архитектурных решений" - она существует сплошь и рядом, хуже того существует вторая проблема. Архитектурные решения когда правильные - принимаются ДОЛГО. Причем именно что большими буквами.

в TDD, BDD за это отвечает понятие code coverage и рефакторинг как процесс - то есть чтобы нам было НЕ страшно рефакторить.
Но для того чтобы code coverage возник - нужно написать первую версию функционала. в итоге мы понимаем что первая версия покрытая тестами будет скорее всего неверная если мы будем писать быстро или нужно будет долго думать над архитектурой.
Эту проблему решает Gherkin - так как появлясь вначале как спецификация: позволяет подумать о сценариях использования и не писать код первой версии. 

На эту проблему нарывались все - а давайте вначале напишем MVP а потом будем рефакторить. 

Поэтому еще одно противоречии

```
Нужно иметь функционал чтобы принять правильное архитектурное решение
НО
Не нужно иметь функционал, так как мы будем долго его разрабатывать
```

**Comment by allustin** [comment]
Если подытожить все противоречия то выходит

Идеальный результат формулируется следующим образом

```
Система инструментов не создавай новых сущностей и не вызывая вредных явлений позволяет:
* Разрабатывать функционал без его разработки
* Внедрять типовые конфигурации
* Рефакторить решения  
убирая негативные факторы:
* не знания 1С-никами Ghekrin, TDD, BDD, GIT
* показывая специалистам разработки по промышленному потенциальные проблемы
```

Напомню - кто забыл или не знал: 

Согласно методике Куба качества продуктов 1С - в 1С мире все наоборот.

* в "соседнем" мире - всё абстрагируется
* в 1С мире - все декомпозируется

если кто не знает - стоит посмотреть "наше веселье" прошлого года 

https://www.youtube.com/playlist?list=PL2zlgf113YhGATW26_WNp7T07FsHgVJpn

Что является решением в данном случае я думаю понятно - некая "Серебряная Пуля" ;-)

хотя если в реальности - то на самом деле в общем мы создаем или должны создать 

* потенциальные **протекатели** абстракций для обычных 1С-ников
* **абстрагаторы** для тех кто постиг дзен правильной разработки
и **адаптаторы** между протекателями и адаптаторами

собственно - в качестве вброса на эту тему указан так называемый радар 
https://github.com/silverbulleters/vanessa-behavior/blob/develop/doc/radars/2015-12.png

Обратите внимание:

* TDD,BDD позволяет сдвинуть "техническое здоровье продукта"
* Gherkin позволяет сдвинуть "здоровье владения продуктом"

ну а остальные инструменты в этом направлении готовятся - так как год разработчика 1С только объявлен и "пока идет январь"

С другой стороны - кто и куда будет двигать здоровье своего продукта автоматизировано - вообще не важно.
Кто-то хочет начать с TDD - @g-ones **reborn_v4** ему в руки
Кто-то хочет начать с Gherkin - слава богу
Кто-то хочет изучит Git, CI, CD - тоже отлично

Главное движение.

То есть решением в данном случае является комплект инструментов развивающихся каждый для своего определенного процесса

А на самом деле - задача решается построением надсистемы над спором. 
То есть "помогатели" улучшать качество. Или адаптаторы

Таким образом - простой ответ @g-ones на твой вопрос

* с TDD-шниками не надо ничего делать, когда у тебя "протечет" продукт, сам станешь TDD-ником - а учитывая что я знаю, что у тебя продуктов 7-мь: ближайшие 2 года тебе это не светит ;-)

* "TDD-шникам" прокомментирую - как только возникнет проблема с 
  * неверными архитектурными решениями первых версий продуктов
  * длинным сроком окупаемости в Ваших командах по внедрению TDD,BDD
  * отторжением методик TDD, BDD в силу непрофильного образования образования   

Вспомните про это обсуждение и мои доводы

указав на него ссылку согласно лицензии

<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Лицензия Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />Произведение «<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Методика ADD в 1С</span>» созданное автором по имени <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/allustin" property="cc:attributionName" rel="cc:attributionURL">Alexey Lustin</a>, публикуется на условиях <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">лицензии Creative Commons «Attribution-NonCommercial-NoDerivatives» («Атрибуция — Некоммерческое использование — Без производных произведений») 4.0 Всемирная</a>.<br />Основано на произведении с <a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/silverbulleters/vanessa-services/issues/14" rel="dct:source">https://github.com/silverbulleters/vanessa-services/issues/14</a>.<br />Разрешения, выходящие за рамки данной лицензии, могут быть доступны на странице <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/silverbulleters/vanessa-services/issues/14" rel="cc:morePermissions">https://github.com/silverbulleters/vanessa-services/issues/14</a>.

**Comment by allustin** [comment]
Существует также 2 проблемы которые ТРИЗ не решаются

* организационные
* политические

**Организационно**

*  Серебряная Пуля проводит платные практикумы - поэтому методика внедрения и методики преподавания остаются у нас и обсуждать я их больше не буду. Не обижайтесь. Обратите внимание - что часть этих денежных средств идет фактически на развитие всей этой концепции. Поэтому @g-ones на будущее - такие вопросы стоит задавать на внутренних обсуждениях.

**Политическая**

* есть другие методики и другие методологи со своими инструментами
* другие методологи в основном занимаются консалтингом без публикации своих наработок в OpenSource

поэтому споры методологического характера, которые не выраождающиеся в OpenSource код и контрибьюцию воспринимаются нами как попытка взять методологию, ничего не отдавай взамен. Поэтому при публичных обсуждениях учитывайте это пожалуйста. К участникам текущей дискуссии это я верю не относится.

**Comment by allustin** [comment]
Ну и напоследок

@g-ones 

технически у нас есть только одна проблема

* разница в снипетах:

в behavior

```
////@ЯОткрылФормуVanessaBehavoirВРежимеСамотестирования()
Процедура ЯОткрылФормуVanessaBehavoirВРежимеСамотестирования() Экспорт
	ВызватьИсключение "Не реализовано.";
КонецПроцедуры
```

в xUnit

```
&НаКлиенте
Процедура Тест_ПроверитьРавно() Экспорт  
```

причем - это вообще не проблема.
просто 

* есть epf файлы с тестами
* есть epf файлы с шагами

и это вообще не проблема

потому как есть 2 разных плеера и пусть себе живут на общее благо

**Comment by alehinsasha** [comment]
![2016-01-31_9-30-56](https://cloud.githubusercontent.com/assets/8247178/12700680/9a098bec-c7fd-11e5-81a0-bd8cb6bd0493.png)

**Comment by allustin** [comment]
**ADD наше все**

и вообще http://pytest.org/latest/example/index.html

**Comment by allustin** [comment]
https://youtu.be/pa4MXT4Cw1s

**Comment by allustin** [comment]
https://github.com/silverbulleters/vanessa-bootstrap/commit/a4b8aaad23c6824b3131fb67afa22a925720acf1
