### ISSUE TITLE
Plugin для EDT

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#15]
automigrated to xdd forum

**Comment by allustin** [comment]
https://plus.google.com/+AlexeyLustinSocial/posts/7WFMCt81WNG

Учитывая голосование - лучше попробовать обсудить.

https://snegopat.ru/forum/viewtopic.php?f=1&p=9170&sid=5a04f9beb6928bd5fa4f5fa41b9157b0#p9170

Пока идет развитие Снегопата по встраиванию в 8.x.x, про Eclipse вообще тишина.

Локализацию вывожу в отдельную задачу.

**Comment by Hissin** [comment]
**Тип задачи:** Конкретная

**Общая формулировка:** 
необходимость развития и использования плагина EDT. Локализация плагина

**Противоречие 1:** 
выпускать ли плагин для EDT вообще и под чьей маркой
**Противоречие 2:** 
локализация плагина
**Противоречие 3:** 

**Идеальный конечный результат** 

* 

**Аналоги "в соседнем мире"**

* 

**Формулировка решения:**

* 

**Состав:**

* 

**Поведение:**

* 

~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик" 
* "Красно-эмоциональный матерщинник" 
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист" 
* "Зеленый нарцисс творец" 
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by allustin** [comment]
Варианты

* передать идею snegopat.ru в коллективное владения

предлагается правило

* Vanessa Stack c английским кодом и реквизитами в Eclipse (локализация на русский автоматизировано)

* работа в Конфигураторе - русский код всегда (интерфейсы локализуются автоматизированно)

Появление JAVA в 1С мире

https://zookeeper.apache.org/
http://mesos.apache.org/
детей учат http://club.1c.ru/java/

**Comment by allustin** [comment]
JAVA только для 

* плагинов к серверу 1С
* плагинов к Eclipse

для остального 1С.

https://wiki.eclipse.org/E4/JavaScript

**Comment by allustin** [comment]
https://bitbucket.org/EvilBeaver/1script/issues/237/1script-e4

**Comment by allustin** [comment]
https://youtu.be/S_AhoUSLnV0

**Comment by allustin** [comment]
Вышла 1.2.0 beta - просмотрел код. Видимо все архитектурные решения уже приняты - поэтому можно начинать публикацю плагинов ;-)
