### ISSUE TITLE
i18n, i10n and linter

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#16]
automigrated to xdd forum

**Comment by allustin** [comment]
В довесок ко всему - вот например как ведут себя JavaScript товарищи

http://www.babylscript.com/mappings/ru.html

**Comment by allustin** [comment]
* Реализовать поддержку локализации интерфейса с помощью https://crowdin.com/
* Перевести весь код на английский.
* Совместить с рефакторингом кода и функционала для версии 2.0
* Синтаксис-Помощник - ИнформацияОСистеме:SystemInformation

решить когда переходить на английский стиль кодирования

"Надо кодировать на английском, но не надо кодировать на английском"

```
Яблоко = Новый Структура();
```
транслируется 

```
Yablocko = New Structure();
```

или переводится

```
Apple = New Structure();
```

1. Новый код проходит синтаксис контроль `ПриходнаяНакладная` или `ПрихНакл`
2. Либо транслитерация, либо перевод
3. Дерево кода и её оценку

На досуге посмотреть https://github.com/alecthomas/gometalinter

Интерфейс начинаем прикручивать https://crowdin.com/

**Comment by Hissin** [comment]
Вопрос на потом: конфликты перевода как при кодировании, так и при локализации интерфейса.

**Comment by allustin** [comment]
https://youtu.be/4b6I-vZwHIQ

**Comment by allustin** [comment]
Вишенка на торте http://1c-dn.com/developer_tools/1c_translator/#translationalgorithm

**Comment by allustin** [comment]
https://crowdin.com/project/vanessa-services
