### ISSUE TITLE
step_definitions <= 8.3.7 и => 8.3.8

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#17]
automigrated to xdd forum

**Comment by nixel2007** [comment]
> то есть в связи с выходом 8.3.8 - МОЖНО НЕ ХРАНИТЬ БИНАРНИКИ в GIT

5 копеек - так можно и на прекоммите, но немного коряво.

**Comment by allustin** [comment]
@nixel2007 да можно - только сложновато. Порог вхожения выше. с 8.3.8 можно снижать.

**Comment by allustin** [comment]
Какой предлагается процесс:

* начиная с релиза 1.0 Vanessa Stack мы работаем только исходниками
* сборку делаем в релиз для скачивания

пользователи скачивают релиз, контрибьюторы работают с исходниками

шаги редактируются напрямую в исходниках.

собираются в каталог build

Остаются 3 коллизии:

* обратная совместимость - как не хранить бинари в каталоге steps defition
* нужно будет обяснить как счачивать и сбирать инструментарий по новому
* неуправляемые формы - их на такой подход не перевести

**Comment by allustin** [comment]
Предложение 1:

* с 28 июля отказываемся от поддержки неуправляемого режима. Кладется в отдельную "что-то". Переход на новый 8.3.8 формат разработки. И задокументировать это формат.
* на серверах сборок - использовать 8.3.4,  8.3.5,  8.3.7 и 8.3.8 и т.д. И задокументировать минимальную версию платформы. 8.2 с серверов сборок удаляется.

параметры сборки:

* vanessa-stack-vanilla-code - 8.3.7 и 8.3.8
* комплект патчей для патчинга под старые версии

релизы:

* VanessaStack 0.9.40.epf
* VanessaStack-Legasy-8.3.5 0.9.40.epf

пример:

8.3.8
```
.ПрочитатьJSON() //из платформы

```

8.3.3
```
patch add  ПрочитатьJSON with text from JSON lib by Alex Pereverz
```

**Comment by nixel2007** [comment]
Продолжу мысль по поводу методов объектов.

Мне кажется, тут можно встрять на поддержке этих патчей. На сколько я помню их работу в обычных исходниках они очень чувствительны к не изменению заменяемой строчки. VB будет обновляться, патчи будут некорректными и не применимыми.

На подумать.

**Comment by allustin** [comment]
https://youtu.be/7-idjfRRocs?list=PL2zlgf113YhGd-uTBCJQTp87c11Hdryj8
