### ISSUE TITLE
Обсуждения и освещение вопросов для открытой публики

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-services#18]
Что мы можем обсуждать и рассказывать людям, а что не стоит, или стоит, но в другом формате.

**Comment by allustin** [comment]
Хм. Интересно.

Ты про противоречии - что вроде как мы консультанты-внедренцы практик, а получается отдаем бесплатно.

То есть надо обсуждать, но не надо обсуждать.

В этом противоречие ?

**Comment by Hissin** [comment]
@allustin ну в целом да. где грань того, что мы можем дать в свободном доступе.

**Comment by allustin** [comment]
@Hissin - шарим только код, и то по согласованию.
обсуждение методологические надо убирать. только технические - типа делать BDD Editor как полноценное IDE ;-) и как.

**Comment by allustin** [comment]
В общем обсуждаем только то что может повлиять на следующие категории граждан

* активных контрибьторов oscript, xDrivenDevelopment

если инициаторы мы - начинаем обсуждение на форуме XDD
если инициаторы коллеги - сразу создаем заметку-концепцию

**Comment by artbear** [comment]
Что за форум XDD ?

**Comment by allustin** [comment]
@artbear http://xdd.silverbulleters.org

**Comment by artbear** [comment]
Если говорите про "активных контрибьторов oscript, xDrivenDevelopment",
напоминаю, что у меня, одного из тех самых, активнейших, контрибьюторов :)
нет доступа на этот форум

пн, 2 мая 2016 г. в 19:11, Alexey Lustin <notifications@github.com>:

**Comment by allustin** [comment]
@artbear написано же:

> В общем обсуждаем только то что может повлиять на следующие категории граждан
> активных контрибьторов oscript, xDrivenDevelopment
> если инициаторы коллеги - сразу создаем заметку-концепцию

Форум - это для клиентов и партнеров. Насколько я знаю тебе пока не интересно ни партнерство, ни тем более клиентство.

**Comment by artbear** [comment]
Я всегда за сотрудничество. Мы с тобой обсуждали наше взаимодействие.
В итоге ты сам от него отказался :( хотя обсуждали несколько вариантов.

пн, 2 мая 2016 г. в 21:16, Alexey Lustin <notifications@github.com>:

**Comment by allustin** [comment]
@artbear у меня другая версия событий. но это не тема данного issue
