### ISSUE TITLE
Менеджеры и разработчики и стратеги

### ISSUE THREAD

**Issue by g-ones** [silverbulleters/vanessa-services#19]
Тут случилась очередная коллизия

* менеджерам страшно - так как тут нужно поменять процессы, а это очень страшно
* разработчикам страшно - так как тут нужно ставить какие-то дополнительные программы и о боже, работать в консоли
* стратегам страшно - потому что они не стратеги

ну и в довершении:
* инфраструктурщикам лень - так как на компьютер разработчика нужно ставить какой-то дополнительный софт и "о боже", иногда использовать linux.
 
я это к тому, что текущие внедрения, даже не обучение,  а тупая борьба с идиотизмом и страхи

Противоречие в том, что когда начинаешь внедрять ADD

* c разработчиков которым вроде как не страшно, рядом тусуются менеджеры которым страшно и они саботируют.
*  с менеджеров которым не страшно, рядом обязательно оказываются стратеги или разрабы, которые работают в стиле "страшно ну его нафиг" и опять саботаж.

Идеальный конечные результат - должна быть какая-то система, которая позволяет не боятся инструментария, наверное оставляя процессы неизменными... Не знаю короче. 

@allustin - хочу узнать как быть.

**Comment by alehinsasha** [comment]
По моему рабочая практика когда в каждую группу саботажников берется новый сотрудник @Pr-Mex , не на замену а для ~~заражения~~ внедрения и продвижения ADD. А ещё предлагаю на внедрении, хотя бы на начальном этапе, не использовать аббревиатуру ADD, вместо этого говорить и писать перевод или расшифрованный вариант. А то может по этому и бояться, представьте: начальник собирает всех и говорит "С завтрашнего дня начинаем внедрять ADD" ;). @allustin что скажешь про долю шутки в этой шутке?

**Comment by allustin** [comment]
@g-ones @alehinsasha - не знаю что пока сказать

нашел в #14 следующую цитату

```
поэтому споры методологического характера, которые не вырождаются в OpenSource код и контрибьюцию воспринимаются нами как попытка взять методологию, ничего не отдавай взамен. Поэтому при публичных обсуждениях учитывайте это пожалуйста. К участникам текущей дискуссии это я верю не относится.
```

я бы эту задачу и задачу #18 прикрыл от греха - и перенес на XDD форум, для внутренного обсуждения или вообще тупо в офисе это обсуждать.

пока я могу сказать, что наверное технически надо вернутся к инсталятору/установщику, снижая порог вхождения - это для разработчиков.

@g-ones - плюс в мае начнем запускать "BDD как сервис" - легче старт отдельного разработчика.

Что касается менеджеров - тут же проблема, это SCRUM/Agile и доски. Нет доски - нет нормального BDD, ADD, TDD. 

А стратеги - это вообще SAFe. http://scrumtrek.ru/trainings/view/96/234/

@alehinsasha - пока я не готов это обсуждать.
@g-ones я задачу прикрою.

**Comment by allustin** [comment]
Сделаем первый старт в том числе для менеджеров в рамках вебинара

https://youtu.be/pmvDnlaJLps?list=PL2zlgf113YhGd-uTBCJQTp87c11Hdryj8
