### ISSUE TITLE
Инфраструктурые фичи

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#20]
короткий вопрос - как сделать

* feature файлы на 1Script
* генератор сниппетов
* запускальщик

причем сделать так, чтобы кодовая база VB была единой, добавлялись только формочки

думаю про сборку на 8.3.8 - через vanessa runner двух релизов

* vb как epf
* vb как opm

**Comment by Hissin** [comment]
Добавлю каплю. как минимум надо будет признак внутри фичи, или разграничение мест хранения (подкаталоги структуры компонент)

**Comment by nixel2007** [comment]
@Hissin поясни, пожалуйста. зачем?

**Comment by allustin** [comment]
Предложение 1: (на основе #17 )

Исходим из позиции https://github.com/cucumber/microcuke

* BSL модуль для работы с Gherkin - читатель
* BSL модуль для работы с шагами - вызыватель, его придется пропатчить под поддержку OScript

Виденье - это сборка Vanessa Stack под 1Script с патчами.

Предложения 2:

* библиотечная фича с шаблонными шагами
* Expected1Script

Общее предложение

Ремарка - синхронизовать блок ассертов между 1Script, VB, xUnitReborn

**Comment by allustin** [comment]
Отдельное замечание - наращивать библиотеки и документировать

**Comment by allustin** [comment]
https://github.com/silverbulleters/vanessa-stack-commons/issues/4

**Comment by allustin** [comment]
предложение 2 - оптимальней.

структуру каталога фич нужно выработать под особенности инфраструктуры.

**Comment by allustin** [comment]
Нужно добавить https://github.com/silverbulleters/vanessa-bdd-editor/tree/master/doc
За основу взять ITILv4 и преобразовать структуру каталогов-компонет

**Comment by allustin** [comment]
И сделать https://github.com/silverbulleters/vanessa-behavior/issues/68

**Comment by allustin** [comment]
https://youtu.be/YFndeE5I0AU?list=PL2zlgf113YhGd-uTBCJQTp87c11Hdryj8
