### ISSUE TITLE
Разница между подключением библиотек в режиме инсталятора и контрибьютора

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#4]
Когда я  обычный/типичный разработчик 1C - мне удобней установить Vanessa Stack через MSI и choko
и обновлять в режиме простых вызовов команд

```
chocko install vanessa-stack
chocko update vanessa-stack
```

тогда структура каталогов будет выглядеть
```
<Vanessa Stack>
   Behavior
   Epics
   <Commons>/sb<ИмяБиблиотеки>
```

когда я контрибьютор vanessa-stack то мне  необходимо подключать библиотеки как подмодуль git
и тогда адрес библиотек выглядит примерно так ./vendor/commons/ или ./libs/commons

Противоречие 1: адрес библиотек должен быть настраиваемым, но для контрибьютора он должен иметь значение по умолчанию

Противоречие 2: каталог библиотек в инсталятор установлен как константа, но он должен быть настраиваемым иначе не будут работать зависимости от конечного инструментария 

Расположение библиотек должно быть удобней и для инсталятора и для контрибьютора.

**Comment by Hissin** [comment]
**Тип задачи:** 

**Общая формулировка:**

**Противоречие 1:** 

**Идеальный конечный результат** 

**Аналоги "в соседнем мире"**

**Системный решатель:**

* Задача "надсистемы": 
* Антизадача "надсистемы": 
* Задача "системы": 
* Антизадача "системы": 
* Задача "подситемы": 
* Антизадача "подсистемы": 

**Формулировка решения:**


**Функционал:**



**Состав:**



**Поведение:**



~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик"
* "Красно-эмоциональный матерщинник"
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист"
* "Зеленый нарцисс творец"
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by allustin** [comment]
Получилось так https://youtu.be/NKdPsdP8y1M - проблема шире чем на 30 минут.

**Comment by allustin** [comment]
Ушло в реализацию в рамках 

https://github.com/silverbulleters/vanessa-behavior/issues/140
https://github.com/silverbulleters/vanessa-behavior/issues/139
