### ISSUE TITLE
"Бехавойрист" и его уровни

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-services#5]
Есть закон - все участники должны писать код. Другое дело какой это код - документация, ожидаемый функционал, сценарии контроля поведения или код выполнения.

В режиме разработки с нуля или в режиме внедрения - все пишут код, а проект собирается за один шаг (и собственно развертывается)

Но в этой концепции существуют несколько противоречий применительно к BDD, а именно 3:

Системному аналитику (бизнес-аналитику) удобно писать высокоуровневые фичи формат "Тогда документ провёлся корректно", и совершенно скучно (долго) писать сценарии на конкретных примерах - так как основное его время уходит на общение и драку с заказчиком

Ведущему разработчику 1С (чаще всего методологу по типовой конфигурации) удобно писать секцию формат "Когда в поле введено значение 42" и совершенно скучно опускаться на уровень кода и совершенно "наплевать" на высокоуровневые сценарии системного аналитика

Разработчику кодеру удобней писать "Когда функция _Смысл() получает значение параметра _СамыйПравильныйВопрос Тогда Результат равен 42", в связи с тем что он это делает в режиме разработки и контекста алгоритма и ему нет необходимости сейчас структурировать этот алгоритм до верхнего уровня (до уровня бизнес-пользы), ему достаточно атомарности.

На самом деле идеальным результатом будет концепция инженер бизнес-приложения - когда одна конфигурация = один бехавойрист. И контроль за хаосом структурой фич будет на его стороне (в том числе с помощью Vanessa Cloud Services). Но это уже история обучения и практикумов.

В идеале видится что в BDD editor нужно добавить контроль хаоса фич - скорее всего из теории графов или UML, чтобы построить карту компонентов, сценариев (в том числе вложенных). Но это космос. А вот в Vanessa Behavior необходимо добавить возможность писать атомарные шаги сценариев без привязки к функционалу. То есть тот момент когда feature файл появляется после step-definition.

То есть налицо 2 проблемы:

* Как контролировать качество собранных требований с учетом вложенности и коллективной разработки ?
* Как позволить писать feature файлы на основе step-definition ?

Как решалась проблемы у "соседей" 

* первая проблему соседи решили координально - они разработали концепцию микросервисов и отказались от больших систем типа ERP. И полностью перешли на микропродукты интегрированные по API - в нашей терминологии микроконфигурации. Подобный подход нам не светит - у нас будут ERP, УТ, КА и т.д.

* вторую проблему соседи решили моделью predefined-steps низкоуровневого характера
и фейковыми фичами с названием  "Как программист я хочу небольшие проверки модулей"

примеры

* канареечные шаги https://github.com/selenium-cucumber/selenium-cucumber-ruby/blob/master/doc/canned_steps.md
* проверка поведения без кодирования https://zato.io/docs/test/apitest/step/index.html

**Comment by Hissin** [comment]
прежде чем думать о месте написания, надо продумать структуру. Я так понимаю первый признак качества собранных требований будет как раз наличие вложенных фич (подчиненных фич) т.к. ни одна фича аналитика не может существовать без более глубокой расшифровки
если Жене удобно писать в коде, тогда надо како-либо тег (еще что-то) из которых потом читая код можно будет выдернуть шаги в фичу
Фактически мы можем читая код написанный разработчиком искать необходимые теги и собирать фичу. а потом ее просто корректировать

**Comment by Hissin** [comment]
на счет низкоуровневых фич: как вариант подготовить стандартные фичи (шаблоны) аля: И создалась запись регистра сведений и заполнились поля. как пример. для вызова в более высокоуровневых фичах. Их можно отработать вообще одним проходом по метаданным и по реквизитам.

**Comment by Pr-Mex** [comment]
@allustin 
Ты пишешь
*А вот в Vanessa Behavior необходимо добавить возможность писать атомарные шаги сценариев без привязки к функционалу.*
Для этого можно использовать уже существующий механизм вложенных сценариев.

**Comment by Pr-Mex** [comment]
@Hissin 
Ты пишешь:
*на счет низкоуровневых фич: как вариант подготовить стандартные фичи (шаблоны) аля: И создалась запись регистра сведений и заполнились поля. как пример. для вызова в более высокоуровневых фичах.*
Для этого создаётся механизм под кодовым названием "expected data".

**Comment by Hissin** [comment]
@Pr-Mex я счастлива :) тогда часть проблем закроются. остаются пара вопросов: сбор фичи из текста кода, и сама вложенность фич

**Comment by Pr-Mex** [comment]
Я не совсем понял что такое "сбор фичи из текста кода".
А вложенность сценариев уже поддерживается. Этого хватит, чтобы получить вложенность фич?

**Comment by Hissin** [comment]
@Pr-Mex  почитай выше мой пост.  Это был ответ на сообщение Жени:
[19:18:42] Shenja Sosna: находясь в конфигураторе мне удобней там добавлять код, чем писать сначала в фичу шаги, потом запускать перегенерацию, при этом надо закрыть обработку в конфигураторе, потом необходимо ее заново открыть, открыть форму, модуль и найти таки то место где у меня тесты используются.

**Comment by Pr-Mex** [comment]
Я, честно, не понимаю, что там надо искать в модуле после перегенерации. Все новые шаги всегда добавляются в самый низ модуля.
Насчет переоткрытия форм: в обычном мире такие задачи решаются макросами, например снегопатом. ;-)

**Comment by Pr-Mex** [comment]
*А вот в Vanessa Behavior необходимо добавить возможность писать атомарные шаги сценариев без привязки к функционалу.*
Сейчас в любую epf можно в ручном режиме добавить столько step_definitions, сколько надо.
Для этого надо в процедуру:
ПолучитьСписокТестов()
добавить эти шаги.
После этого их можно использовать при написании фич. 
Для того чтобы контролировать сколько и где у нас существует step_definitions - нам и нужен BDD editor.

**Comment by allustin** [comment]
Вообще данное противоречие связано с один вопросом "Кто пишет фича файлы и сценарии"

Большинство обычных разработчиков 1С пытаются "слиться" и от того и от другого
Аналитики-менеджеры (классические) пытаются слиться от сценариев
Разработчики пытаются слиться от фича файлов.

Это я еще не говорю про ночные сборки, от которых пытаются слиться вообще все. А когда начинаешь говорить что база должна быть пустая - от этого вообще сливаются еще и менеджеры по качеству ;-).

В довершении всего - разные товарищи еще и заявляют что Gherkin "не нужен". Ну и так далее.

**Comment by allustin** [comment]
![image](https://cloud.githubusercontent.com/assets/55323/11887798/b6704618-a548-11e5-95a6-c16833193f41.png)

"Вишенка" - драка между бизнес-аналитиками и программистами за принадлежность языка продолжается даже в стане "кукумберовцев"

**Comment by Pr-Mex** [comment]
Весело.

**Comment by Hissin** [comment]
**Тип задачи:** Абстрактная

**Общая формулировка:** Код должны писать все, но каждый только на своем уровне

**Противоречие 1:** Требуется, чтобы все писали feature-файлы только на своем уровне, однако нет четкого разграничения, какой формат и содержание должны быть в feature-файле на каждом уровне *и всё это нужно к практикуму в марте*, чтобы обучение было правильное

**Идеальный конечный результат** 

**Аналоги "в соседнем мире"**

**Системный решатель:**

* Задача "надсистемы": 
* Антизадача "надсистемы": 
* Задача "системы": 
* Антизадача "системы": 
* Задача "подситемы": 
* Антизадача "подсистемы": 

**Формулировка решения:**


**Функционал:**


**Состав:**

 
**Поведение:**



~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик"
* "Красно-эмоциональный матерщинник"
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист"
* "Зеленый нарцисс творец"
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by allustin** [comment]
Чувствую - это будет глобальное противоречие https://youtu.be/U7I2Gaec7SU

**Comment by Hissin** [comment]
Думаю надо порисовать :
* области применения каждого уровня 
* используемые инструменты
* глубина вопроса/понимания друг друга

Эдакий *.mm уровней и зависимостей. Пусть критикуют

**Comment by allustin** [comment]
Всего будут 4 уровня бехавойриста - это уже понятно

Нужно их просто задокументировать в виде сущностей
Методологию вывести на практикум и зафиксировать FAQ

**Comment by allustin** [comment]
Данное противоречие НЕ противоречие ;-)

методология будет роздана на практикуме, остальное в рамках документирования функционала.

Еще один момент - нам не хватает 3 вида функционала

* метода ВыполнитьШаг()
* помошника по автоподстановке библиотечных шагов
* проверке шагов которые определены в behavior и отсутствуют в фича файлах - https://github.com/silverbulleters/vanessa-behavior/issues/215

@Hissin не забудь создать Draft'ы behavior

**Comment by Pr-Mex** [comment]
Жду драфтов.
