### ISSUE TITLE
Использование ключевых слов внутри функций и архитектура написания фич

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-services#7]
Есть проблема с архитектурой (структурой) написания фич. Разными пользователями будет использоваться разная структура написания фич. Обе они подходят для отработки бихевиором, но для эдитора представляют затруднение в раскладывании на значения в виде: Роли, Цели, Итоги.

Пример:
Вариант1:

Функционал: написание фичи
Как системный аналитик
Я хочу удобный инструмент для написания фич
**Чтобы** быстро и качественно отрабатывать фичи

Вариант2:

Функциона: написание фичи
Как системный аналитик
Я хочу **чтобы** был удобный инструмент для написания фич

Варианты могут быть другие. Но ключевое слово **"Чтобы"** влияет на разложение заголовка в структуру дерева и обратно.

**Comment by Pr-Mex** [comment]
Предлагаю считать, что ключевое слово должно быть с двоеточием. Тогда мы однозначно всё определим.

**Comment by Hissin** [comment]
@Pr-Mex Не думаю, что все начнут сразу подстраиваться под наши условия

**Comment by Pr-Mex** [comment]
Это вопрос соглашений. Парсеру фич тоже надо за что-то цепляться.

**Comment by Hissin** [comment]
можно проверять конечно наличие двух ключевых слов в одной строке, но проблема в том, что строк может быть несколько. Надо продумать все.

**Comment by Pr-Mex** [comment]
Я в любом случае за спецсимволы.
В самом Gherkin они уже есть.
Например надо писать "Сценарий:", а не просто "Сценарий", т.е. без двоеточия будет ошибка.

**Comment by Hissin** [comment]
**Тип задачи:** 

**Общая формулировка:**

**Противоречие 1:** 

**Идеальный конечный результат** 

**Аналоги "в соседнем мире"**

**Системный решатель:**

* Задача "надсистемы": 
* Антизадача "надсистемы": 
* Задача "системы": 
* Антизадача "системы": 
* Задача "подситемы": 
* Антизадача "подсистемы": 

**Формулировка решения:**


**Функционал:**



**Состав:**



**Поведение:**



~~~Заполняется во время обсуждения~~~

Критика:

* "Белый флегматичный аналитик"
* "Красно-эмоциональный матерщинник"
* "Черный неконструктивный критик-тролль"
* "Желтый молодой оптимист"
* "Зеленый нарцисс творец"
* "Синий фундаменталист революционер"

Оценка:

Нравится 1 ..+10
Не нравится -1 .. -10
Что нового дает ?
Преимущества ?
Предположения (допущения) ?
Плюсы ?
Минусы ?

**Comment by allustin** [comment]
пообщался с ребятами из Gherkin.

Пока принимаем что:

* BDD Editor и Behavior ведут синтаксический контроль с помощью commons
* commons повторяет полностью AST дерево (то есть дерево языка) которое соответствует Gherkin3 и пока выдумывть нечегое.

Если мы сможем убедить Аслакак и Мэта в том что мы изобрели какой-то новый кейс - я лично подам issues в проект Gherkin3

Так что это не противоречие - а просто требование на commons.
