### ISSUE TITLE
Хранение исходных хаотичных вбросов заказчика (до переучивания)

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-services#8]
Т.к. пока заказчики не работают с Gherkin, и в какое-то ближайшее время этого не произойдет:

В каком виде и где хранить исходные хаотичные вбросы заказчика, которые пока нельзя форматировать в фича-файлы? Потоковый текст пришедший на анализ. 
Может это должна быть еще доп. временная папка для анализа? (Пример: вброс по CRM от....)
Чтобы при формировании письма заказчику фича-файлы ссылались на исходный текст заказчика. 

Со стороны заказчика будет выглядеть так:

Функционал:  Анализ исходных вбросов
    Как Заказчик
    Я хочу передать аналитику исходный текст своих пожеланий
    Чтобы аналитик проанализировать и вернул связанные доработки со ссылкой на исходный текст

Сценарий: передача вброса
    Когда я формирую исходные вбросы в понятном мне варианте потоковой информации
    И отправляю аналитику
    Тогда аналитик фиксирует их у себя для последующего анализа

Сценарий: получение анализа
    Когда я получаю проанализированные и структурированные фича-файлы
    И открываю исходный текст
    И открываю фича-файл
    Тогда я вижу их в последовательном порядке структуры исходного текста
    И я вижу привязки какой фича-файл к какому пункту исходного текста относится.

**Comment by allustin** [comment]
У нас есть волшебный каталог docs внутри проекта, внутри которого стоит наверное создать каталог **strange** и там хранить в формате Markdown.

Пока вроде так

**Comment by Hissin** [comment]
**Тип задачи:** Конкретная

**Общая формулировка:** Хранение исходных вбросов от заказчика

**Противоречие 1:** Требуется хранить исходные вбросы заказчика, однако они хаотические, разбросанные, противоречащие, не связанные

**Идеальный конечный результат** исходные вбросы хранятся в структуре бизнес-компонент и к ним привязаны feature-файлы

**Аналоги "в соседнем мире"**

**Системный решатель:**

* Задача "надсистемы": автоматизированное распределение вбросов заказчика и соотношение с бизнес-компонентами
* Антизадача "надсистемы": создание бизнес-компонент исходя из вбросов заказчика
* Задача "системы": хранение файлов в структуре каталогов бизнес-компонент
* Антизадача "системы": файлы вбросов ссылаются на бизнес-компоненты
* Задача "подситемы": текст вброса структурирован по структуре конфигурации
* Антизадача "подсистемы": конфигурация структурирована под текст запроса

**Comment by allustin** [comment]
Вот так вот https://youtu.be/1zlav_lrVuc

@Hissin - надо будет сделать автозапись, а то немного пропущена вводная часть

Сама задача опять связана с процессом, нежеле чем с техническими трудностями. Поэтому скорее всего нужно только 3 кнопки. Дальше посмотрим

**Comment by Hissin** [comment]
@allustin - Можно наверное вводную не делать и вопрос закрыть нашим внутренним решением, после обдумывания. Ребятам это не мешает, это автоматизация нашей боли. 
Кнопки ок. Принято

**Comment by allustin** [comment]
берем еще раз в обсуждение.

тут подали идею - а если вброс от заказчика поступил по почте и он хочет сохранить переписку.

а если вброс от заказчика вообще поступил в отдел продаж по системе CRM

**Comment by allustin** [comment]
@Hissin написал 6 листов рассуждения и обоснования инструментария
Что-то меня напрягает это выкладывать публично. Своруют концепцию.
Задачу закрываю - перенес в PMO.

если коротко:

* оставляем расширение drafts
* к марту сделаем на oscript небольшой инструмент
