### ISSUE TITLE
возможные доп проверки в ассерты

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-services#9]
мы ассертами закроем часть стандартных проверок.
Но возникает ситуация, когда нам необходимо осуществить дополнительные проверки, которые часто применяются, типа:

  * И в ТЧ добавилась строка
  * И в ТЧ количество строк 
  * И в папке создался файл с именем
  * И в папке есть файлы с расширением feature 
и т.д.

Возможно сейчас напишу странное и ерунду, но:

Также очень часто приходится описывать двойные проверки в случае если "истина" и в случае если "ложь", которые различаются только итогом выполнения, чаще просто при одном выполняется, а при другом нет. Было бы удобно описать в одном функционале, если итог заранее предопределен как Выполнять/Не выполнять. (Не берем в рассмотрение когда разный итог при выполнении условия)
Например:
По идее мы должны описать два раза:

Когда нажимаем кнопку добавить
И указан справочник-источник
И если в справочнике есть записи
Тогда в ТЧ заполняем строки

Когда нажимаем кнопку добавить
И указан справочник-источник
И если в справочнике нет записей
Тогда в ТЧ не заполняем строки

Было бы удобно объединить в один функциональный вызов:

Когда нажимаем кнопку добавить
И указан справочник-источник
Тогда в ТЧ заполнились необходимые строки

С вызовом проверки:
    1. в справочнике есть данные, в папке есть файлы, или в том месте откуда заполняем есть данные
    2. заполнилась ли ТЧ в случае наличия исходников

Т.к. в режиме проверки поведения сценариев он два раза выходит на выполнение одних и тех же действий. Но в рамках одной фичи это не страшно. А вот в рамках проверки всего функционала, например на БП 3.0 это увеличит время проверки.

**Comment by Hissin** [comment]
**Тип задачи:** Абстрактная

**Общая формулировка:** Создание дополнительных ассертов на исключающие действия при получении ответа "Истина" или "Ложь"

**Противоречие 1:** Необходимы дополнительные ассерты, однако они могут описаться стандартным языком Gerkhin *и всё это нужно к практикуму в марте*, чтобы обучение было правильное

**Противоречие 2:** Необходимы дополнительные ассерты, однако нет четкого понимания и ограничения по количеству их создания *и всё это нужно к практикуму в марте*, чтобы обучение было правильное

**Идеальный конечный результат** сокращение написание кода используя дополнительные ассерты на взаимоисключающие действия (выполнять/не выполнять, заполнять/не заполнять и т.д.)

**Аналоги "в соседнем мире"**

**Системный решатель:**

* Задача "надсистемы": Система сама определяет необходимо ли ей выполнять данное действие
* Антизадача "надсистемы": Действие определяет выполняться ли ему исходя из параметров
* Задача "системы": существуют дополнительные ассерты на взаимоисключающие действия
* Антизадача "системы": на каждое действие существуют взаимоисключающие ассерты
* Задача "подситемы": проверка переданного значения на соответствие ожидаемому результату и исходя из него оно выполняется или не выполняется
* Антизадача "подсистемы": результат выполняется только тогда, когда в него передастся необходимое для его выполнения значение

**Формулировка решения:**


Функционал:

**Comment by allustin** [comment]
решение будет в стиле https://github.com/silverbulleters/vanessa-behavior/commit/22f2147c3a796477f2145dba0a8ecfb13f2c807c

**Comment by allustin** [comment]
по примеру https://github.com/selenium-cucumber/selenium-cucumber-ruby/blob/master/doc/canned_steps.md

**Comment by allustin** [comment]
@Pr-Mex придумал концепцию

ExpectedForms и ExpectedAll - тут конечно нужны контрибьюторы, но попробуем еще раз разобрать проблему.

есть еще одна методика ускоряющая разработку. 

```не писать ассерты вообще, а работать с объектами так как будто они уже являются тем чем должны```,читаемый текст ошибки не нужен - так все равно отлаживать ;-): надо чтобы шаг либо упал, либо нет.

работать такая методика со сложными объектами в 1С, хотя в ruby было удобней -"там все есть объект"

```
a = my_system.getString();
//вместо assertEqualType(a, String) вызываем метод который есть только у строки
а.concat("если это упадет, значит a нифига не строка");
```

**Comment by Pr-Mex** [comment]
Немного дополню.
В концепте сейчас три пункта:
ExpectedSteps - сделаны генератор кода и библиотека
ExpectedForms - сделаны генератор кода и библиотека
ExpectedReports - тоже самое сделано и для отчётов
ExpectedData - не сделано. Тут помощь контрибьютеров очень пригодится.

**Comment by allustin** [comment]
2 вопроса я предлагаю обсудить на архкоме совместно:

* как подключать библиотеки Expected<ЧтоТо> если библиотеку разработали в отдельном проекте git - например контрибьюторы или мы сами

хуже того - сделаю вброс: мы потихоньку приблизились к накоплению библиотек типа

* ExpectedUT11
* ExpectedBP30
* ExpectedERP ;-)
и т.д.

и еще - @Hissin здесь больше опять больше методологии внедрения и процесса разработки. Поверь мне - 2015 год показал, что больше подобными вещами интересуются менеджеры и бизнесмены, которые совершенные... ну вообщем ты в курсе. 

И закрыть эту задачу - потому как это уже не противоречие в общем, а необходимость сделать следующее:

* повысить удобство работы с библиотеками, чтобы не писать повторно одних и тех же проверок.
* накопить библиотеки дальше.
* разработать инструмент поиска подобных шагов, чтобы было удобней выявлять коллизии следующего характера

```
Когда запущено приложение "bash.exe"
Когда запущена команда "bash.exe"
Когда запущена команда системы "bash.exe"
```

**Comment by allustin** [comment]
Решение

* форма показа существующих процедур
* синтаксис помошник шагов
* текстовый шаблоны -для Конфигуратора
* текстовые шаблоны для редакторов
.
Повторное обсуждение - 30 марта.

git текстовые шаблоны https://github.com/alehinsasha/Text-patterns-1C в качестве git-flow

**Comment by allustin** [comment]
https://youtu.be/_RZ5H3mxvSw
